<p>
    <?php _e("CUF (<b>C</b>lean <b>U</b>upload <b>F</b>older) will search all the files from your upload folder and try to find if this files are attached/used on any Post and Page, if any reference is found, the plugin will tell you that the image is used.", 'cuf'); ?>
    <br/>
    <b class="label label-danger" ng-if="options.backup==0" ><?php _e("Warning the backup system is deactivated, see the option page", 'cuf'); ?></b>
    <br/>
    <b class="label label-danger" ng-if="wc.active==1"><?php _e("Warning you use wooCommerce plugin and you can have false 'not used' label, you have two options, you can select all wooCommerce sizes in the ignore size list or download the PRO version", 'cuf'); ?></b>
</p>
<h3><?php _e("Where i can foud CUF PRO", 'cuf'); ?></h3>
<p>
   <b> <a href="https://apps.nicearma.com/product/cuf-clean-upload-folder/"><?php _e("CUF PRO version have some useful features:", 'cuf'); ?></a></b>
    <ol>
        <li><strong><?php _e("Compatibility with WooCommerce",'cuf'); ?></strong> <?php _e("(the main WooCommerce plugin, not other extends plugins)", 'cuf'); ?></li>
        <li><strong><?php _e("Delete all automatic button,",'cuf'); ?></strong> <?php _e(" this will go page by page and delete all file not used", 'cuf'); ?></li>
        <li><?php _e("Restore all backup", 'cuf'); ?></li>
        <li><?php _e("Delete all backup", 'cuf'); ?></li>
    </ol>
</p>
<h3><?php _e("How to support this plugin", 'cuf'); ?></h3>
<p><?php _e("You can give a good or bad review at ", 'cuf'); ?><a href="https://wordpress.org/support/view/plugin-reviews/cuf-clean-upload-folder"><?php _e("CUF reviews", 'cuf'); ?></a><?php _e(" or buy the CUF PRO version", 'cuf'); ?></p>
<h3><?php _e("Why i have to do Backup?", 'cuf'); ?></h3>
<p>
    <?php _e("This plugin will delete files and information from your server and the database, so we recommend to do a BACKUP every time you want to use this plugin.", 'cuf'); ?>
</p>
<h3><?php _e("Is the backup system from the CUF plugin enough?", 'cuf'); ?></h3>
<p>
    <?php _e("Yes and no, if you have the backup option active, the plugin will try to do one backup of every file you are try to delete, but this is not the main purpose of the CUF plugin, so is not bullet proof", 'cuf'); ?>
    <br/>
    <?php _e("Under plugins page there are various more effective plugins you can use. We suggest you try one", 'cuf'); ?>
</p>
<h3><?php _e("Are the file actually not being not used?", 'cuf'); ?></h3>
<p>
    <?php _e("Yes and not, the 'unused' label, tells you that the file.fileType (toto.jpg) is not found in any Post/Page/Shortcode, this does not mean that a page generated by a plugin is not using this file and therefore if you delete said file, be aware, that it could be that a plugin is using it.", 'cuf'); ?>
    <br/>
    <?php _e("To go further:", 'cuf'); ?>
    <br/>
    <?php _e("So if you have another plugin, for example 'Easy load X' that use the example.jpg in one HTML code or Javascript, if the CUF plugin can't find any reference at the database, it will return a false 'unused' label", 'cuf'); ?>

</p>